# Generated by Django 5.1.7 on 2025-03-29 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=51, verbose_name='task')),
                ('describtion', models.TextField(verbose_name='describtion of the task')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('done', 'Done'), ('delayed', 'Delayed'), ('notstarted', 'NotStarted, Start it!')], default='not_start', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low priority'), ('mid', 'Mid priority'), ('high', 'High priority')], default='mid', max_length=10)),
                ('due_to', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
