# Generated by Django 5.1.7 on 2025-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('done', 'Done'), ('delayed', 'Delayed'), ('notstarted', 'Not Started, Start it!')], default='not_start', max_length=20),
        ),
    ]
