# Generated by Django 5.1.7 on 2025-03-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='describtion',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='nothign', verbose_name='description of the task'),
            preserve_default=False,
        ),
    ]
