# Generated by Django 5.1.7 on 2025-04-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_alter_comment_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='media',
            new_name='comment_pics',
        ),
    ]
